window.ARITH = window.ARITH || {};
ARITH["eng-voice"] = {
  title: "Active & Passive Voice",
  short: "Who does what to whom: be + past participle, the optional by-phrase, and when the passive is the right choice",
  grade: "College ENGL 1xx · grammar",
  hours: 4,
  voice: "plain",
  eyebrow: "Grammar & Usage · voice",
  hero: `<span class="c3">The soup</span> <span class="c4">was</span> <span class="c2">eaten</span> <span class="c5">by the cat</span>.`,
  lede: `In the active voice the subject does the action (<i>The cat ate the soup</i>). In the passive, the thing acted on becomes the subject and the doer moves to an optional <i>by</i>-phrase (<i>The soup was eaten by the cat</i>).`,
  plain: `<p>Most sentences tell you who did something and what they did it to: <i>The cat ate the soup.</i> The doer, <i>the cat</i>, comes first, as the subject. That is the <b>active voice</b>.</p>
<p>You can turn the sentence around so that the thing that had something done to it comes first: <i>The soup was eaten by the cat.</i> Now <i>the soup</i> is the subject, the verb has become <i>was eaten</i>, and the cat has moved to the end, after <i>by</i>. That is the <b>passive voice</b>. The passive always has a form of <i>be</i> (or, in casual speech, <i>get</i>) and a past participle: <i>was eaten</i>, <i>is taken</i>, <i>has been sent</i>.</p>
<p>The <i>by</i>-phrase is optional, and most passives in real writing leave it out: <i>My bike was stolen.</i> That is useful when you don’t know the doer, when the doer doesn’t matter, or when you want to keep talking about the thing acted on. It can also be a way of hiding who is responsible: <i>Mistakes were made.</i></p>
<p>Voice is not tense. A passive can be in any tense, and the tense lives on <i>be</i>: <i>is taken, was taken, will be taken, has been taken, is being taken</i>. The main verb is always the past participle.</p>`,
  formal: `<p><b>Voice</b> is the grammatical category that relates the subject of a clause to the action of its verb. In the <b>active voice</b> the subject is the <b>agent</b> (the doer); in the <b>passive voice</b> the subject is the <b>patient</b> (the receiver), the noun phrase that would be the direct object of the active clause. The passive verb phrase is a form of the auxiliary <b>be</b> followed by the <b>past participle</b> of the main verb; the agent, if it is expressed at all, appears in a <b>by-phrase</b>. Any auxiliaries come before passive <i>be</i>, and passive <i>be</i> carries the tense or the aspect.</p>
<div class="display">Active: <span class="c1">agent</span> <span class="c2">V</span> <span class="c3">object</span><br>Passive: <span class="c3">object</span> <span class="c4">be</span> <span class="c2">V-en</span> (<span class="c5">by</span> <span class="c1">agent</span>)<br>is taken · was taken · will be taken<br>is being taken · was being taken<br>has been taken · had been taken<br>will have been taken · must be taken</div>
<p>Only verbs with an object have a passive. <b>Intransitive</b> verbs (<i>arrive, sleep, happen</i>) and <b>linking</b> verbs (<i>seem, become, taste</i> + adjective) have none. A few transitive verbs of state, called <b>middle verbs</b>, also resist it: <i>have</i> (possess), <i>lack, resemble, cost, weigh, fit, suit</i> (<i>*Two pounds are weighed by the parcel</i>). A verb with two objects has two passives: <i>They gave her a medal</i> → <i>She was given a medal</i> / <i>A medal was given to her</i>. A prepositional verb can passivise with its preposition left behind: <i>Someone has slept in this bed</i> → <i>This bed has been slept in</i>. In a <b>get-passive</b> (<i>My bike got stolen</i>) the auxiliary is <i>get</i>; it is informal, always describes an event, and often implies that the subject was affected for better or worse. A <b>stative</b> (or adjectival) passive describes a resulting state rather than an action: <i>The museum is closed on Mondays</i>, <i>She was very interested</i>. The participle works as an adjective there (it takes <i>very</i>, and no by-agent is implied).</p>
<p>Two confusions follow from the forms. The passive is not the past tense: <i>The letter is written in pencil</i> is present passive. And the past participle is not the simple past: irregular verbs separate them (<i>took/taken, wrote/written, broke/broken</i>), so <i>*The window was broke</i> is nonstandard. Nor is every <i>be</i> + participle passive: <i>have</i> + participle is the perfect (<i>has arrived</i>), and <i>be</i> + <i>-ing</i> is the progressive.</p>
<p>Modern grammar describes the same facts with different labels. Huddleston and Pullum’s <i>Cambridge Grammar of the English Language</i> treats voice as a system of the whole clause, calls the by-phrase an <b>internal complement</b>, and distinguishes the <b>verbal passive</b> (an event) from the <b>adjectival passive</b> (a state). It also recognises <b>bare passives</b>, participial clauses with passive meaning and no <i>be</i>: <i>a nation <u>conceived in liberty</u></i>. It treats passive <i>be</i> as an auxiliary but analyses <i>get</i> as an ordinary lexical verb taking a participle complement, which is why the get-passive needs <i>do</i> in questions (<i>Did it get stolen?</i>).</p>`,
  legend: [
    { c: "c1", sym: `A`, name: "Agent (doer)", desc: "Who or what does the action: the subject of an active clause, or the object of <i>by</i> in a passive." },
    { c: "c2", sym: `V`, name: "Main verb", desc: "The lexical verb. In the passive it is always the past participle: <i>taken, written, prepared</i>. Cyan also marks the other auxiliaries (<i>will, has</i>)." },
    { c: "c3", sym: `R`, name: "Receiver (patient)", desc: "What the action is done to: the direct object of the active, promoted to subject in the passive." },
    { c: "c4", sym: `be`, name: "Passive auxiliary", desc: "<i>Be</i> (or <i>get</i>) in the right tense: <i>is, was, will be, has been, is being</i>. It carries the tense; the participle never changes." },
    { c: "c5", sym: `by`, name: "By-phrase", desc: "<i>by</i> + the agent, in object case (<i>by her, by them</i>). Optional: most passives leave it out." }
  ],
  steps: { title: "How to turn an active sentence into the passive", items: [
    `Find the <span class="c2">main verb</span> and check that it has a <span class="c3">direct object</span>. No object, no passive.`,
    `Move the <span class="c3">object</span> to the front as the new subject. A pronoun changes case: <i>me → I, them → they</i>.`,
    `Note the tense and aspect of the active verb phrase, and give that tense to <span class="c4"><i>be</i></span>, keeping any modal or <i>have</i> in front: <i>has taken → has been taken</i>.`,
    `Make <i>be</i> agree with the new subject (<i>the sample <u>was</u>, the samples <u>were</u></i>).`,
    `Put the main verb in its <span class="c2">past participle</span> form, which for irregular verbs differs from the past tense (<i>chose → chosen</i>).`,
    `Decide whether to keep the old subject as a <span class="c5">by-phrase</span> (object case: <i>by her</i>). Keep it if it is new or important information; drop it if it is obvious, unknown or vague.`,
    `Read both versions aloud and choose the one that keeps the sentence’s topic in subject position and its news at the end.`
  ] },
  example: {
    prompt: `Rewrite in the passive: <i>The committee has rejected our proposal.</i> Then decide whether to keep the agent, and check the result against the active.`,
    lines: [
      { math: `<span class="c1">The committee</span> <span class="c2">has rejected</span> <br><span class="c3">our proposal</span>`, note: "Agent the committee, verb has rejected (present perfect), direct object our proposal. Rejected takes an object, so a passive exists." },
      { math: `<span class="c3">Our proposal</span> …`, note: "The object becomes the subject." },
      { math: `has rejected → has <span class="c4">been</span> <br><span class="c2">rejected</span>`, note: "Present perfect active is have + participle; the passive keeps have and inserts been (the participle of be) before the main verb." },
      { math: `<span class="c3">Our proposal</span> <span class="c4">has been</span> <br><span class="c2">rejected</span> <span class="c5">by the committee</span>.`, note: "Has agrees with the singular subject proposal. The old subject becomes the by-phrase." },
      { math: `<span class="c3">Our proposal</span> <span class="c4">has been</span> <br><span class="c2">rejected</span>.`, note: "If the reader already knows who decided, drop the by-phrase. If the point is who rejected it, keep it, or use the active." },
      { math: `Check: <span class="c1">the committee</span> rejected it ✓`, note: "Turn it back: the by-phrase noun is the doer of rejected, and the tense (present perfect) is unchanged. Same meaning, different focus." }
    ],
    answer: `<span class="c3">Our proposal</span> <span class="c4">has been</span> <span class="c2">rejected</span> (<span class="c5">by the committee</span>). Same tense (present perfect), carried by <i>has been</i>; the main verb is the past participle <i>rejected</i>.`
  },
  why: `<p>Voice decides what a sentence is about. English puts its topic in subject position and its news at the end, so choosing active or passive is choosing which participant the reader follows. In a paragraph about a vaccine, <i>The vaccine was developed in 2020 by a team in Oxford</i> keeps the vaccine as the topic and saves the news (who made it) for last. The passive is the normal choice when the agent is unknown (<i>My car was stolen</i>), obvious (<i>He was arrested</i>), or deliberately general, as in scientific methods sections (<i>The samples were centrifuged for ten minutes</i>) and laws (<i>Notice shall be given in writing</i>).</p>
<p>The passive also lets a writer leave out responsibility. <i>Mistakes were made</i> names no one; <i>Shots were fired</i> says nothing about who fired. Handbooks’ advice to prefer the active is advice to name the doer when the doer matters, and to avoid strings of agentless passives that make prose vague and slow. Reading critically means noticing which agents a writer leaves out.</p>`,
  careers: [
    { role: "Scientific researcher", use: "Writes methods sections in the conventional passive (samples were stored at 4 °C) and results and discussion increasingly in the active (we found)." },
    { role: "Attorney or paralegal", use: "Drafts contract clauses where voice decides obligations: the tenant shall pay rent is clear about who must act; rent shall be paid is not." },
    { role: "Technical writer", use: "Uses active imperatives for instructions (press the reset button) and the passive for system behaviour where the agent is the software." },
    { role: "Journalist or copy editor", use: "Checks that headlines and reports do not hide agents (protesters were injured versus police injured protesters) and attribute actions accurately." },
    { role: "Public relations and crisis communications specialist", use: "Chooses between an accountable active apology (we made an error) and a passive one, knowing readers notice the difference." },
    { role: "ESL / EFL instructor", use: "Teaches passive formation across tenses and the past participle forms of irregular verbs, a persistent difficulty for learners." }
  ],
  life: [
    "Reading an official statement and noticing that “errors were made” never says who made them.",
    "Writing a lab report in the expected style: the solution was heated, not I heated the solution.",
    "Turning a vague complaint (“the form was never sent”) into an actionable one (“your office never sent the form”).",
    "Choosing “was born”, the only natural way to talk about a birth, which nearly always leaves the agent out."
  ],
  fields: [
    { name: "Biology and chemistry", use: "Lab reports and journal articles use the passive for procedures, so that the method, not the experimenter, is the subject." },
    { name: "Law", use: "Statutes use agentless passives (shall be punished) and courts read voice closely to decide who owes a duty." },
    { name: "Journalism and media studies", use: "Studies of news language measure how often passives and nominalisations remove agents from reports of violence or policy." }
  ],
  prereqWhy: {
    "eng-patterns": "Only the pattern with a direct object (S–V–DO and the patterns built on it) has a passive: the passive promotes that object to subject. Intransitive and linking patterns have none."
  },
  unlocksWhy: {},
  beyond: [
    { field: "Composition I", why: "Revision for clarity starts with voice: finding agentless passives and deciding when the doer should be named." },
    { field: "Advanced Composition & Rhetoric", why: "Topic and focus, given and new information, and the ethics of agency in persuasive and institutional writing." },
    { field: "Introduction to English Linguistics", why: "Voice as a syntactic transformation, argument structure, and why some transitive verbs have no passive." },
    { field: "History of the English Language", why: "Old English used weorþan as a passive auxiliary beside beon/wesan; the get-passive is a modern development." }
  ],
  mistakes: [
    { wrong: `"<i>The guests have arrived</i> is passive, because it has a past participle."`, fix: `A passive needs <i>be</i> (or <i>get</i>) + participle. <i>Have</i> + participle is the <b>perfect</b>, active: the guests did the arriving. <i>Arrive</i> has no object, so it cannot be passive.` },
    { wrong: `"Passive means past: <i>The rules are explained on page 3</i> is in the past tense."`, fix: `Voice and tense are separate. <i>Are explained</i> is <b>present</b> passive; <i>were explained</i> is past passive; <i>will be explained</i> is future passive.` },
    { wrong: `"<i>The window was broke during the storm.</i>"`, fix: `The passive takes the past <b>participle</b>, not the past tense: <i>was <u>broken</u></i>. Likewise <i>was chosen</i> (not <i>chose</i>), <i>was written</i>, <i>was taken</i>.` },
    { wrong: `"Never use the passive."`, fix: `Use it when the agent is unknown, obvious or unimportant, or when the receiver is the topic: <i>Penicillin was discovered in 1928.</i> Prefer the active when the doer matters and the passive would hide it.` },
    { wrong: `"<i>It is believed by many experts that…</i>"`, fix: `A by-phrase on an impersonal passive is clumsy. Name the agent in the active (<i>Many experts believe that…</i>) or drop it if it adds nothing.` }
  ],
  practice: [
    { q: `Active or passive? (a) <i>The bridge was built in 1932.</i> (b) <i>The workers were building a bridge.</i> (c) <i>The bridge has collapsed.</i>`,
      a: `(a) <b>Passive</b>: <i>was</i> + past participle <i>built</i>; the bridge received the action. (b) <b>Active</b>: <i>were</i> + <i>-ing</i> is the past progressive; the workers are the doers. (c) <b>Active</b>: <i>has</i> + participle is the present perfect; <i>collapse</i> is intransitive and has no passive.` },
    { q: `Rewrite in the passive, keeping the tense: <i>The nurses are taking blood samples.</i>`,
      a: `<i>Blood samples <u>are being taken</u> (by the nurses).</i> Present progressive active <i>are taking</i> becomes present progressive passive: <i>are</i> (progressive) + <i>being</i> (passive <i>be</i>) + <i>taken</i> (past participle). <i>Are</i> agrees with the plural <i>samples</i>.` },
    { q: `Rewrite in the active, supplying a sensible agent: <i>The decision to close the clinic was made last week without any public meeting.</i> Which version is better in a news story, and why?`,
      a: `<i>The city council <u>decided</u> last week, without any public meeting, to close the clinic.</i> (The agent must come from context.) In news the active is better here: who decided is the important information, and the passive hides it. The passive would suit a story where the decision-maker is already known or beside the point.` },
    { q: `Which of these have a passive, and what is it? (a) <i>They offered Sam the job.</i> (b) <i>Sam resembles his father.</i> (c) <i>Everyone laughed at the proposal.</i> (d) <i>Sam seemed nervous.</i>`,
      a: `(a) Two passives, because <i>offer</i> has two objects: <i>Sam was offered the job</i> and <i>The job was offered to Sam</i>. (b) None: <i>resemble</i> is a middle verb (*<i>His father is resembled by Sam</i>). (c) A prepositional passive: <i>The proposal was laughed at (by everyone)</i>. (d) None: <i>seem</i> is a linking verb and <i>nervous</i> a subject complement, not an object.` }
  ],
  origin: `The term comes from Latin grammar: <i>vox</i> translated the Greek <i>diathesis</i>, and Greek distinguished active, middle and passive. Old English had only one inflected passive form (<i>hātte</i>, “is called”) and otherwise built passives with <i>beon/wesan</i> or <i>weorþan</i> + participle, the ancestor of today’s <i>be</i>-passive. The advice to avoid the passive is modern: William Strunk’s <i>The Elements of Style</i> (1918) says “Use the active voice”, and George Orwell’s “Politics and the English Language” (1946) says never to use the passive where you can use the active. Linguists such as Geoffrey Pullum have since pointed out that several of Strunk and White’s “passive” examples are not passive at all.`,
  stories: [
    { title: "All Men Are Created Equal", book: "The Declaration of Independence", author: "Thomas Jefferson et al.", year: 1776, kind: "Political document", where: "Second paragraph", scene: "declaration", focus: ["ag", "vb", "rc", "be", "by"],
      tags: { ag: { name: "Agent (doer)", c: "c1", test: "Who performs the action." }, vb: { name: "Main verb", c: "c2", test: "The lexical verb; a past participle in the passive." }, rc: { name: "Receiver", c: "c3", test: "What the action is done to." }, be: { name: "Passive be", c: "c4", test: "A form of be before a past participle." }, by: { name: "By-phrase", c: "c5", test: "by + the agent." } },
      tokens: `We_ag hold_vb these_rc truths_rc to be self-evident , that all_rc men_rc are_be created_vb equal , that they_rc are_be#are2 endowed_vb by_by their_ag Creator_ag with certain unalienable Rights , …`,
      notes: { we: "Active: we, the signers, are the doers of hold.", hold: "Active main verb, present tense: we hold these truths.", truths: "Direct object of hold: the receiver in an active clause.", men: "Subject of a passive clause: all men receive the action of creating.", are: "Passive be, present tense. Are created = be + past participle.", created: "Past participle. No by-phrase: the clause does not name the creator here.", they: "Subject of the second passive; it refers back to all men.", are2: "Passive be again, present tense, agreeing with they.", endowed: "Past participle of endow (to give, to provide with).", by: "The by-phrase: it names the agent of endowed.", creator: "The agent, inside the by-phrase. In the active: their Creator endowed them with certain unalienable Rights." },
      note: `One sentence, both voices. The main clause is <b>active</b>: <span class="c1">We</span> <span class="c2">hold</span> <span class="c3">these truths</span>. The two <i>that</i>-clauses that state the truths are <b>passive</b>, so that <i>all men</i> stay the subject: <span class="c3">all men</span> <span class="c4">are</span> <span class="c2">created</span> equal, <span class="c3">they</span> <span class="c4">are</span> <span class="c2">endowed</span> <span class="c5">by their Creator</span>. The first passive has no agent; the second names one in a by-phrase, and readers naturally take the same Creator as the understood agent of <i>created</i>. The passives keep the focus on the people who hold the rights.` },
    { title: "I Was Born in Tuckahoe", book: "Narrative of the Life of Frederick Douglass, an American Slave", author: "Frederick Douglass", year: 1845, kind: "Autobiography", where: "Chapter I", scene: "tidewater", focus: ["rc", "be", "vb", "ag"],
      tags: { rc: { name: "Receiver (passive subject)", c: "c3" }, be: { name: "Passive be", c: "c4" }, vb: { name: "Main verb", c: "c2" }, ag: { name: "Agent / active subject", c: "c1" } },
      tokens: `I_rc was_be born_vb in Tuckahoe , near Hillsborough , and about twelve miles from Easton , in Talbot county , Maryland . I_ag#i2 have_vb no accurate knowledge of my age , never having seen any authentic record containing it .`,
      notes: { i: "Subject of a passive: Douglass is the one who was born, not the one who acted.", was: "Passive be, past tense, agreeing with I.", born: "The past participle of bear in its birth sense, used only in the passive. There is no by-phrase, as almost always with born.", i2: "Subject of an active clause.", have: "Active. Have meaning possess is a middle verb with no passive: *No accurate knowledge is had by me is not English." },
      note: `<i>Was born</i> is the most common agentless passive in English: the mother is the agent of <i>bear</i>, but the sentence is about the child, so the passive puts <span class="c3">I</span> in subject position and needs no by-phrase. The second sentence is <b>active</b>, with <i>have</i>, a verb that has no passive at all. Of the two finite verbs, one is passive and one active, and Douglass is the subject of both.` },
    { title: "Conceived in Liberty", book: "Gettysburg Address", author: "Abraham Lincoln", year: 1863, kind: "Speech", where: "First sentence", scene: "battlefield", focus: ["ag", "vb", "rc", "be"],
      tags: { ag: { name: "Agent (doer)", c: "c1" }, vb: { name: "Main verb / participle", c: "c2" }, rc: { name: "Receiver", c: "c3" }, be: { name: "Passive be", c: "c4" } },
      tokens: `Four score and seven years ago , our_ag fathers_ag brought_vb forth_vb upon this continent a_rc new_rc nation_rc : conceived_vb in liberty , and dedicated_vb to the proposition that all_rc#all men_rc are_be created_vb#created equal .`,
      notes: { fathers: "The agent and subject of the active main clause.", brought: "Active verb, simple past. Brought forth (produced, created) is a phrasal verb.", forth: "The particle of the phrasal verb brought forth.", nation: "Direct object of brought forth: the receiver.", conceived: "A past participle with passive meaning and no be: a nation [that was] conceived in liberty. Modern grammars call this a bare passive.", dedicated: "A second bare passive, joined to conceived by and. Both modify nation.", all: "All men is the subject of the passive clause inside the proposition.", are: "Passive be, present tense.", created: "Past participle; the same agentless passive as in the Declaration, which Lincoln is quoting." },
      note: `The main clause is <b>active</b>: <span class="c1">our fathers</span> <span class="c2">brought forth</span> <span class="c3">a new nation</span>. Then two past participles describe the nation, <span class="c2">conceived</span> in liberty and <span class="c2">dedicated</span> to the proposition, each a passive without <i>be</i> and without an agent. The proposition itself is a full passive clause, <span class="c3">all men</span> <span class="c4">are</span> <span class="c2">created</span> equal, quoted from the Declaration of Independence. One active verb, three passive participles: the founders act once, and the nation is shaped.` }
  ]
};
