window.ARITH = window.ARITH || {};
ARITH["eng-verbals"] = {
  title: "Verbals: Gerunds, Participles & Infinitives",
  short: "Verb forms that work as nouns, adjectives and adverbs: -ing, -ed and to- forms, their phrases, and the tests that tell them apart",
  grade: "College ENGL 1xx · grammar",
  hours: 5,
  voice: "plain",
  eyebrow: "Grammar & Usage · verbals",
  hero: `<span class="c1">Swimming</span> <span class="c2">helps</span> <span class="c3">tired</span> kids <span class="c4">to relax</span>.`,
  lede: `A verbal is a verb form that does another part of speech’s job: a <b>gerund</b> works as a noun, a <b>participle</b> as an adjective, an <b>infinitive</b> as a noun, adjective or adverb. Verbals have no tense of their own, so they can never be the main verb of a sentence.`,
  plain: `<p>Verbs can be borrowed for other jobs. In <i>Swimming is good exercise</i>, <i>swimming</i> names an activity, the way a noun does: you could say <i>It is good exercise</i>. That borrowed <i>-ing</i> form is a <b>gerund</b>.</p>
<p>In <i>the swimming children</i> or <i>the exhausted hikers</i>, the verb form describes a noun, like an adjective: <i>which children? the swimming ones</i>. That is a <b>participle</b>: present (<i>-ing</i>) or past (<i>-ed</i>, or an irregular form like <i>broken</i>). In <i>I want to swim</i> or <i>She left early to swim</i>, <i>to</i> + the plain verb is an <b>infinitive</b>, and it can work as a noun, an adjective or an adverb.</p>
<p>A verbal keeps some verb habits. It can take an object and modifiers, making a <b>verbal phrase</b>: <i>taking a walk that day</i>, <i>reading by the window</i>, <i>to buy a car</i>. But it has no tense and no subject that agrees with it, so a verbal phrase on its own is never a sentence: <i>*Taking a walk that day.</i> is a fragment.</p>
<p>Not every <i>-ing</i> word is a verbal. In <i>She is swimming</i>, <i>is swimming</i> is the main verb (the progressive). The test is the job: replace the word with <i>it</i>, with an adjective, or ask whether it belongs with <i>is</i>.</p>`,
  formal: `<p>A <b>verbal</b> is a <b>non-finite</b> form of a verb: it is not marked for tense, person or number, and it cannot serve as the predicate of an independent clause. Traditional grammar recognises three. A <b>gerund</b> is the <i>-ing</i> form used as a noun: subject (<i>Swimming relaxes me</i>), direct object (<i>She enjoys swimming</i>), object of a preposition (<i>no possibility of taking a walk</i>), or subject complement (<i>Her job is teaching</i>). A <b>participle</b> is used as an adjective: the <b>present participle</b> (<i>-ing</i>) is active in meaning (<i>a rising tide</i>), the <b>past participle</b> (<i>-ed/-en</i>) is usually passive (<i>a broken window</i>), and the <b>perfect participle</b> is <i>having</i> + past participle (<i>Having missed the bus, Leo walked</i>). An <b>infinitive</b> is the base form, usually marked by <i>to</i>; it works as a noun (<i>To err is human</i>; <i>She wants to leave</i>), an adjective (<i>a place to stay</i>), or an adverb (<i>She saved to buy a car</i> = in order to). The <b>bare infinitive</b> (no <i>to</i>) follows modals (<i>must go</i>), <i>make, let</i> and causative <i>have</i>, verbs of perception (<i>saw her leave</i>), and optionally <i>help</i>.</p>
<div class="display"><span class="c1">Gerund</span>: -ing as noun → swap for <i>it</i><br><span class="c3">Participle</span>: -ing/-ed as adjective<br>   → swap for a <i>who/which</i> clause<br><span class="c4">Infinitive</span>: (to) + base<br>   noun → <i>it</i> · adjective → <i>which</i><br>   adverb → <i>in order to</i><br><span class="c2">Not a verbal</span>: be + -ing (progressive),<br>   be/have + -en (passive, perfect)</div>
<p>A verbal heads a <b>verbal phrase</b> that keeps the verb’s complements and modifiers: <i>[taking <u>a walk</u> <u>that day</u>]</i>, <i>[to buy <u>a car</u>]</i>. Verbals also keep voice and aspect: <i>being seen</i>, <i>having left</i>, <i>to have finished</i>, <i>to be told</i>. The understood subject of a verbal is supplied by context, usually the subject of the main clause, which is why misplaced verbal phrases dangle. When a gerund needs its own subject, formal written English puts it in the <b>possessive</b> (<i>I appreciate <u>your</u> helping us</i>; <i>We heard of <u>Ana’s</u> winning</i>); the objective case (<i>him leaving</i>) is standard in speech and common in edited prose, especially with nouns. A <b>split infinitive</b> places an adverb between <i>to</i> and the verb (<i>to boldly go</i>). It is grammatical and often the clearest order (<i>to more than double</i>); the objection to it is a nineteenth-century stylistic preference, and current handbooks advise splitting when the alternative is awkward or ambiguous.</p>
<p>The same <i>-ing</i> word can be any of three things: a gerund, a participle, or part of a finite progressive verb phrase (<i>She <u>is teaching</u></i>). Some verbs take only a gerund object (<i>enjoy, finish, avoid</i>), some only an infinitive (<i>want, decide, hope</i>), and some take both with a change of meaning: <i>We stopped resting</i> (quit) versus <i>We stopped to rest</i> (in order to).</p>
<p>Modern grammars analyse verbals differently. Huddleston and Pullum’s <i>Cambridge Grammar of the English Language</i> notes that the gerund and present participle have had the same form since Middle English and calls it one form, the <b>gerund-participle</b>. What handbooks call a verbal phrase it calls a <b>non-finite clause</b> (it can have its own subject: <i>[your helping us]</i>, <i>[the rain having stopped]</i>), and it treats infinitival <i>to</i> as a subordinator rather than part of the verb.</p>`,
  legend: [
    { c: "c1", sym: `-ing<sub>N</sub>`, name: "Gerund", desc: "An <i>-ing</i> form doing a noun’s job: <i>Swimming relaxes me</i>. Replace it with <i>it</i> or <i>that</i>." },
    { c: "c2", sym: `V`, name: "Finite (main) verb", desc: "The tensed verb of the clause: <i>relaxes, is teaching, was written</i>. Not a verbal." },
    { c: "c3", sym: `-ing/-en<sub>A</sub>`, name: "Participle", desc: "An <i>-ing</i> or past participle form doing an adjective’s job: <i>the rising tide</i>, <i>exhausted by the climb</i>." },
    { c: "c4", sym: `to V`, name: "Infinitive", desc: "<i>To</i> + the base form (or the bare base after <i>make, let</i> or a modal): noun, adjective or adverb." },
    { c: "c5", sym: `[ … ]`, name: "Verbal phrase", desc: "The verbal with its own objects and modifiers: <i>[taking a walk that day]</i>. It never has tense." }
  ],
  steps: { title: "How to identify a verbal and its job", items: [
    `Find the <span class="c2">finite verb</span> of each clause: the one that changes for tense (<i>is/was</i>, <i>enjoys/enjoyed</i>). Any other verb form is a candidate verbal.`,
    `If an <i>-ing</i> word follows <i>be</i> and the subject is doing the action (<i>She is teaching</i>), it is part of the finite verb (progressive). If a past participle follows <i>be</i> or <i>have</i> (<i>was written, has arrived</i>), it is a passive or perfect verb. Stop: these are not verbals.`,
    `Try <i>it</i> or <i>that</i> in place of the whole phrase. If the sentence still works, it is a noun: a <span class="c1">gerund</span> (<i>-ing</i>) or an <span class="c4">infinitive</span> used as a noun.`,
    `Try turning it into a <i>who/which</i> clause on a nearby noun. If that works, it is adjectival: a <span class="c3">participle</span> (<i>-ing</i>, <i>-ed/-en</i>) or an adjectival infinitive (<i>a place to stay</i> = a place where one can stay).`,
    `For a <i>to</i>-form, try <i>in order to</i>. If it answers <i>why?</i>, it is an adverbial infinitive.`,
    `Mark the whole <span class="c5">verbal phrase</span>: the verbal plus its objects and modifiers. Check that it is attached to a sentence with a finite verb, not standing alone.`
  ] },
  example: {
    prompt: `Name every verbal and its job: <i>Having missed the bus, Leo decided to walk, and walking in the rain cured his bad mood.</i>`,
    lines: [
      { math: `<span class="c2">decided</span> · <span class="c2">cured</span>`, note: "The finite verbs: decided and cured change for tense (decides, cures). Everything else verb-like is a candidate verbal." },
      { math: `<span class="c5">[<span class="c3">Having missed</span> the bus]</span>`, note: "A perfect participle (having + past participle) with its object the bus. It describes Leo: Leo, who had missed the bus, decided… So it is a participial phrase." },
      { math: `decided <span class="c5">[<span class="c4">to walk</span>]</span> → <br>decided <i>it</i> ✓`, note: "The it-test works (awkward but grammatical), and the phrase answers decided what?: an infinitive used as a noun, the direct object." },
      { math: `<span class="c5">[<span class="c1">walking</span> in the rain]</span> <br><span class="c2">cured</span> …`, note: "Walking in the rain is the subject of cured. No be in front of it, so it is not a progressive." },
      { math: `<i>It</i> cured his bad mood ✓`, note: "The it-test confirms a noun job: walking is a gerund, heading the gerund phrase walking in the rain." },
      { math: `Check: three verbals, <br>two finite verbs`, note: "Read each verbal phrase alone: Having missed the bus. To walk. Walking in the rain. None is a sentence, which confirms they are non-finite." }
    ],
    answer: `<span class="c3">Having missed</span> (perfect participle; the phrase modifies <i>Leo</i>), <span class="c4">to walk</span> (infinitive as noun, object of <i>decided</i>), <span class="c1">walking</span> (gerund, subject of <i>cured</i>; phrase <i>walking in the rain</i>). The finite verbs are <span class="c2">decided</span> and <span class="c2">cured</span>.`
  },
  why: `<p>Verbals let a writer pack an action into a single slot of a sentence. Instead of two clauses (<i>Leo had missed the bus. He walked to work.</i>) one participial phrase does the work: <i>Having missed the bus, Leo walked to work.</i> Gerunds turn actions into things you can talk about (<i>Editing takes time</i>), and infinitives state purposes and plans (<i>to reduce costs</i>). Most of the variety in mature prose sentences comes from verbal phrases.</p>
<p>They are also behind several common errors. A verbal phrase written as a sentence is a fragment. An introductory participial or infinitive phrase borrows the subject of the main clause, so when the wrong subject follows, the modifier dangles. A series that mixes gerunds and infinitives breaks parallelism (<i>I like hiking, to swim, and biking</i>). And choosing between <i>stopped to talk</i> and <i>stopped talking</i> changes the meaning entirely.</p>`,
  careers: [
    { role: "Editor or copy editor", use: "Fixes dangling participles, verbal fragments and unparallel series of gerunds and infinitives in manuscripts." },
    { role: "ESL / EFL instructor", use: "Teaches which verbs take gerunds, infinitives or both (enjoy doing, want to do, stop doing / stop to do), a hard area for learners." },
    { role: "Technical writer", use: "Writes procedure headings as gerunds (Installing the driver) and purpose statements as infinitives (To reset the device, hold…)." },
    { role: "Computational linguist", use: "Builds part-of-speech taggers and parsers that must decide whether an -ing word is a gerund, participle or progressive verb." },
    { role: "Speech-language pathologist", use: "Assesses children’s use of non-finite forms (infinitives, -ing complements) as a measure of grammatical development." },
    { role: "Grant or proposal writer", use: "States aims as parallel infinitive phrases (to expand access, to train staff, to measure outcomes)." }
  ],
  life: [
    "Writing a résumé where every bullet starts with a parallel verb form.",
    "Reading a sign like “Flying planes can be dangerous” and noticing the two readings (gerund or participle).",
    "Choosing between “I forgot to lock the door” and “I forgot locking the door”, which mean different things.",
    "Spotting that “Hoping to hear from you soon.” at the end of an email is a fragment, fine in a closing but not in a report."
  ],
  fields: [
    { name: "Linguistics", use: "Non-finite clauses, control (who is the understood subject of to leave in She promised to leave) and the history of the -ing form." },
    { name: "Foreign-language study", use: "Translating verbals into languages that use an infinitive where English uses a gerund (Spanish nadar es bueno, swimming is good)." }
  ],
  prereqWhy: {
    "eng-phrases": "A verbal phrase is a phrase headed by a verbal, with the verb’s objects and modifiers inside it; bracketing phrases is how you find where it begins and ends."
  },
  unlocksWhy: {
    "eng-parallelism": "Parallel series most often go wrong by mixing verbal types: <i>to hike, swimming and to bike</i>. Naming each form is the first step in matching them.",
    "eng-modifier-placement": "A dangling modifier is usually an introductory participial or infinitive phrase whose understood subject is not the subject of the main clause."
  },
  beyond: [
    { field: "Composition I", why: "Sentence combining with participial phrases, and fixing verbal fragments and dangling modifiers in drafts." },
    { field: "Introduction to English Linguistics", why: "Non-finite clauses, control and raising verbs, and the gerund-participle as one form." },
    { field: "Advanced Composition & Rhetoric", why: "Cumulative sentences built from participial and absolute phrases, the signature of descriptive prose style." },
    { field: "History of the English Language", why: "The Old English infinitive in -an and the inflected infinitive with to, and how the gerund and participle endings merged as -ing." }
  ],
  mistakes: [
    { wrong: `"In <i>She is teaching chemistry</i>, <i>teaching</i> is a gerund."`, fix: `After <i>be</i>, with the subject doing the action, <i>-ing</i> is part of the finite verb <i>is teaching</i> (present progressive). Compare <i>Her job is teaching</i>, where the job does not teach: there <i>teaching</i> is a gerund, a subject complement.` },
    { wrong: `"<i>Having finished the report.</i>" written as a sentence.`, fix: `A verbal phrase has no finite verb, so alone it is a fragment. Attach it to a clause: <i>Having finished the report, she went home.</i>` },
    { wrong: `"Every <i>-ing</i> word in front of a noun is a gerund: <i>a sleeping baby</i>."`, fix: `<i>Sleeping</i> describes the baby (a baby that is sleeping): a participle. In <i>a sleeping bag</i> the bag is not asleep; it is a bag for sleeping, so <i>sleeping</i> is a gerund used as a noun modifier.` },
    { wrong: `"Never split an infinitive."`, fix: `Splitting is grammatical; the rule is a nineteenth-century preference. <i>To more than double</i> cannot be rephrased without splitting, and <i>to really understand</i> is clearer than <i>really to understand</i>. Avoid only long, clumsy splits.` },
    { wrong: `"<i>I appreciate him helping us</i>" in a formal paper.`, fix: `Formal writing prefers the possessive before a gerund, because the gerund is a noun: <i>I appreciate <u>his</u> helping us</i>. The objective is normal in speech.` }
  ],
  practice: [
    { q: `Gerund, participle or infinitive? (a) <i>Reading</i> relaxes me. (b) The man <i>reading</i> the paper is my uncle. (c) I like <i>to read</i>.`,
      a: `(a) <b>Gerund</b>, subject of <i>relaxes</i> (<i>It relaxes me</i>). (b) <b>Present participle</b>; the phrase <i>reading the paper</i> modifies <i>man</i> (the man who is reading the paper). (c) <b>Infinitive</b> used as a noun, object of <i>like</i> (<i>I like it</i>).` },
    { q: `Mark the verbal phrase and the verbal’s object: <i>The coach asked us to run five laps around the field.</i>`,
      a: `The verbal phrase is <i>[to run five laps around the field]</i>; the infinitive <i>to run</i> takes the object <i>five laps</i> and the adverbial <i>around the field</i>. <i>Us</i> is the object of <i>asked</i> and the understood subject of <i>to run</i>.` },
    { q: `Explain the difference: (a) <i>She stopped to talk to him.</i> (b) <i>She stopped talking to him.</i>`,
      a: `(a) <i>To talk</i> is an <b>adverbial infinitive</b> of purpose: she stopped (what she was doing) in order to talk to him. (b) <i>Talking to him</i> is a <b>gerund phrase</b>, the direct object of <i>stopped</i>: she quit talking to him. The verb <i>stop</i> takes both, with different meanings.` },
    { q: `Classify each <i>-ing</i> word and justify: <i>Being tired, she was dreading the long drive, though driving at night usually calmed her.</i>`,
      a: `<i>Being</i> (tired): present participle; the phrase <i>being tired</i> modifies <i>she</i> (she, who was tired…). <i>Dreading</i>: part of the finite verb <i>was dreading</i> (past progressive; she is doing the dreading), not a verbal. <i>Driving</i> (at night): gerund, subject of <i>calmed</i> (<i>it usually calmed her</i>). <i>Drive</i> in <i>the long drive</i> is an ordinary noun, not a verbal.` }
  ],
  origin: `The terms come from Latin grammar: <i>gerundium</i>, <i>participium</i> (a word that “shares” in both verb and adjective) and <i>infinitivus</i> (“unlimited”, not limited by person or number). In Old English the infinitive ended in <i>-an</i> (<i>singan</i>), and <i>to</i> was used with an inflected form (<i>to singenne</i>); the verbal noun ended in <i>-ung/-ing</i> and the present participle in <i>-ende</i>. In Middle English the two endings fell together as <i>-ing</i>, which is why gerund and participle look alike today. The objection to split infinitives dates from the nineteenth century; H. W. Fowler’s <i>Dictionary of Modern English Usage</i> (1926) mocked writers who contort sentences to avoid them.`,
  stories: [
    { title: "To Be, or Not to Be", book: "Hamlet", author: "William Shakespeare", year: 1603, kind: "Play", where: "Act III, Scene I", scene: "elsinore", focus: ["inf", "g", "fv"],
      tags: { inf: { name: "Infinitive", c: "c4", test: "To + base form, or a bare base form sharing an earlier to." }, g: { name: "Gerund", c: "c1", test: "An -ing form doing a noun’s job." }, fv: { name: "Finite verb", c: "c2", test: "The tensed main verb of a clause." } },
      tokens: `To_inf be_inf , or not_inf to_inf#to2 be_inf#be2 , that is_fv the question : ¶ Whether~’tis nobler in the mind to_inf#to3 suffer_inf ¶ The slings and arrows of outrageous fortune , ¶ Or to_inf#to4 take_inf arms against a sea of troubles , ¶ And by opposing_g end_inf them ?`,
      notes: { to: "To be: an infinitive used as a noun. The pair to be, or not to be is the topic, picked up again by that.", be: "The base form after to. Here be means to exist, to go on living.", not: "Not negates the infinitive, placed before to.", to2: "The second infinitive, joined by or.", be2: "Base form, completing not to be.", is: "The finite verb of the first line: that is the question. Is has tense; the infinitives do not.", to3: "To suffer: an infinitive used as a noun, the real subject of ’tis (it is nobler to suffer…).", suffer: "Base form; its object is the slings and arrows of outrageous fortune.", to4: "Or to take arms: the second choice, another noun infinitive.", take: "Base form, with its object arms.", opposing: "A gerund, object of the preposition by: by opposing (them).", end: "A bare infinitive sharing the earlier to: (to) take arms … and (to) end them." },
      note: `The soliloquy is built on <b>infinitives used as nouns</b>. <span class="c4">To be</span> and <span class="c4">not to be</span> are the subject that <i>that</i> sums up before the only finite verb of the line, <span class="c2">is</span>. The second question compares two more infinitives, <span class="c4">to suffer</span> and <span class="c4">to take</span> arms, both the delayed subject of <i>’tis</i> (it is nobler to suffer… or to take arms…), and <span class="c4">end</span> is a bare infinitive sharing <i>to</i> with <i>take</i>. The one <span class="c1">gerund</span>, <i>opposing</i>, is the object of <i>by</i>. Five infinitives and one gerund: Hamlet thinks in actions he has not yet performed.` },
    { title: "Having Little or No Money", book: "Moby-Dick; or, The Whale", author: "Herman Melville", year: 1851, kind: "Novel", where: "Chapter 1, Loomings", scene: "whaler", focus: ["pt", "ph", "inf", "fv"],
      tags: { pt: { name: "Participle", c: "c3", test: "A verb form doing an adjective’s job; having + past participle is the perfect participle, but having alone is present." }, ph: { name: "Verbal phrase", c: "c5", test: "The verbal with its objects and modifiers." }, inf: { name: "Infinitive", c: "c4" }, fv: { name: "Finite verb", c: "c2" } },
      tokens: `Call me Ishmael . Some years ago — never mind how long precisely — having_pt little_ph or_ph no_ph money_ph in_ph my_ph purse_ph , and_ph nothing_ph particular_ph to_inf interest_inf me_ph#me2 on_ph shore_ph , I thought_fv I would_fv sail_fv about a little and see_fv the watery part of the world .`,
      notes: { having: "A present participle. Its phrase runs to shore and describes I, the subject of thought.", money: "Object of having: little or no money.", nothing: "A second object of having, joined by and: (having) nothing particular to interest me.", to: "To interest: an infinitive used as an adjective. It modifies nothing particular (nothing that would interest me).", interest: "Base form, with its own object me.", me2: "Object of the infinitive interest.", thought: "The finite verb of the main clause, simple past. Everything before I is waiting for it.", would: "Modal, the finite part of would sail … and see.", sail: "A bare infinitive after the modal would, part of the finite verb phrase.", see: "Another bare infinitive after would, joined to sail by and." },
      note: `Melville delays his main clause behind a long <b>participial phrase</b>: <span class="c3">having</span> <span class="c5">little or no money in my purse, and nothing particular to interest me on shore</span>, which modifies <i>I</i>. Inside it, <i>having</i> has two objects, and the second carries an <b>adjectival infinitive</b>, <span class="c4">to interest</span> me, describing <i>nothing particular</i>. Only then comes the finite verb, <span class="c2">thought</span>. The phrase is attached to the right subject, so it does not dangle.` },
    { title: "No Possibility of Taking a Walk", book: "Jane Eyre", author: "Charlotte Brontë", year: 1847, kind: "Novel", where: "Chapter I, first sentence", scene: "moor-window", focus: ["g", "ph", "fv"],
      tags: { g: { name: "Gerund", c: "c1" }, ph: { name: "Gerund phrase", c: "c5" }, fv: { name: "Finite verb", c: "c2" } },
      tokens: `There was_fv no possibility of taking_g a_ph walk_ph that_ph day_ph .`,
      notes: { was: "The finite verb: there was, past tense.", taking: "A gerund, object of the preposition of. It test: no possibility of it.", walk: "Object of the gerund taking: verbals keep their objects.", day: "That day is a noun phrase used adverbially, modifying taking (when?)." },
      note: `The novel’s first sentence turns on one <b>gerund</b>. After the preposition <i>of</i> only a noun can follow, so <span class="c1">taking</span> is doing a noun’s job, yet it still behaves like a verb inside its phrase: it has an object, <span class="c5">a walk</span>, and an adverbial, <span class="c5">that day</span>. The whole gerund phrase is the object of <i>of</i>. Replace it with <i>it</i> (<i>no possibility of it</i>) and the sentence holds.` }
  ]
};
