window.ARITH = window.ARITH || {};

ARITH["eng-verbs"] = {
  title: "Verbs: Tense, Aspect & Mood",
  short: "Verb forms, auxiliaries, the twelve tense–aspect combinations and mood",
  grade: "College ENGL 1xx · grammar",
  hours: 6,
  voice: "plain",
  eyebrow: "Grammar & Usage · the verb phrase",
  hero: `<span class="c1">She</span> <span class="c3">will</span> <span class="c3">have</span> <span class="c3">been</span> <span class="c2">sailing</span>`,
  lede: `A verb phrase is a main verb with up to four auxiliaries in front of it, always in the same order. Each auxiliary adds one idea: when the event is placed (tense), how it is viewed (aspect), and whether it is asserted as fact (mood and modality).`,
  plain: `<p>Every clause has a verb, and the verb is the only word that can tell you <b>when</b>. Compare <i>She sails</i> with <i>She sailed</i>: the ending moves the whole sentence into the past. A <b>main verb</b> carries the meaning (<i>sail, write, be</i>). In front of it can come <b>auxiliary</b> ("helping") verbs: the three primary auxiliaries <i>be</i>, <i>have</i> and <i>do</i>, and the <b>modals</b> <i>can, could, may, might, must, shall, should, will, would</i>. In <i>She will have been sailing</i>, the main verb is <i>sailing</i> and the other three words are auxiliaries.</p>
<p>Most verbs have <b>five forms</b>: the base (<i>take</i>), the <i>-s</i> form (<i>takes</i>), the past (<i>took</i>), the past participle (<i>taken</i>) and the present participle (<i>taking</i>). <b>Regular</b> verbs make the past and past participle with <i>-ed</i> (<i>walk, walked, walked</i>); about two hundred <b>irregular</b> verbs do something else (<i>go, went, gone</i>; <i>put, put, put</i>). <i>Be</i> is the most irregular of all, with eight forms: <i>be, am, is, are, was, were, been, being</i>.</p>
<p>Textbooks speak of <b>twelve tenses</b>: three times (past, present, future) times four aspects. <b>Simple</b> presents an event as a whole (<i>she sailed</i>). <b>Progressive</b>, made with <i>be</i> + <i>-ing</i>, shows it in progress (<i>she was sailing</i>). <b>Perfect</b>, made with <i>have</i> + past participle, looks back on it from a later point (<i>she had sailed</i>). <b>Perfect progressive</b> combines the two (<i>she had been sailing</i>). A useful way to see the difference is with three moments: the time you speak, the time you are talking about, and the time the event happened. The lab draws all three.</p>
<p>Finally, <b>mood</b> says what kind of claim the verb makes. The <b>indicative</b> states and asks (<i>He is on time</i>). The <b>imperative</b> gives orders (<i>Be on time</i>). The <b>subjunctive</b> survives in a few frames: demands (<i>We insist that he <b>be</b> on time</i>) and unreal conditions (<i>If I <b>were</b> you</i>). The modal verbs do most of the rest, marking possibility, necessity, permission and ability.</p>`,
  formal: `<p>The <b>verb phrase</b> (VP) is a <b>main</b> (lexical) verb preceded by up to four <b>auxiliaries</b> in a fixed order, each of which determines the form of the verb after it:</p>
<div class="display"><span class="c3">modal</span> + base · <span class="c3"><i>have</i></span> + past participle (perfect) · <span class="c3"><i>be</i></span> + present participle (progressive) · <span class="c3"><i>be</i></span> + past participle (passive) · <span class="c2">main verb</span><br><span class="dim">e.g.</span> <span class="c3">might</span> <span class="c3">have</span> <span class="c3">been</span> <span class="c3">being</span> <span class="c2">repaired</span></div>
<p>The first verb of a VP is <b>finite</b>: it carries tense and, in the present, agreement with the subject (<i>she <b>has</b> sailed</i>, <i>they <b>have</b> sailed</i>). Auxiliaries share the <b>NICE</b> properties that main verbs lack in present-day English: <b>N</b>egation with <i>not</i> (<i>is not</i>), <b>I</b>nversion in questions (<i>Has she?</i>), <b>C</b>ode, or standing in for an omitted verb phrase (<i>He should!</i>), and <b>E</b>mphasis (<i>She <b>did</b> sail</i>). A clause with no auxiliary borrows the dummy auxiliary <i>do</i> for these (<b>do-support</b>): <i>She sailed → She did not sail → Did she sail?</i> Main-verb <i>be</i> needs no <i>do</i> (<i>She was not careful</i>), and neither, in British usage, does possessive <i>have</i> (<i>I haven't a clue</i>). A <b>linking</b> (copular) verb such as <i>be, seem, become</i> joins the subject to a subject complement (<i>It was the best of times</i>); a <b>transitive</b> verb takes a direct object (<i>wrote a letter</i>); an <b>intransitive</b> verb takes none (<i>She sailed</i>).</p>
<p><b>Tense</b> locates a situation in time relative to the moment of speech; <b>aspect</b> presents its internal shape (complete, in progress, or completed before a reference point). Following Reichenbach (1947), let <span class="m c4">S</span> be speech time, <span class="m c4">R</span> reference time and <span class="m c5">E</span> event time:</p>
<div class="display">simple past <i>she sailed</i>: <span class="c5">E</span> = <span class="c4">R</span> &lt; <span class="c4">S</span><br>present perfect <i>she has sailed</i>: <span class="c5">E</span> &lt; <span class="c4">R</span> = <span class="c4">S</span><br>past perfect <i>she had sailed</i>: <span class="c5">E</span> &lt; <span class="c4">R</span> &lt; <span class="c4">S</span><br>future perfect <i>she will have sailed</i>: <span class="c4">S</span> &lt; <span class="c4">R</span>, <span class="c5">E</span> &lt; <span class="c4">R</span><br>progressive (any tense): <span class="c4">R</span> falls inside the span of <span class="c5">E</span></div>
<p>Traditional handbooks count twelve tenses (past, present, future × simple, progressive, perfect, perfect progressive). Modern grammars, including Huddleston and Pullum's <i>Cambridge Grammar of the English Language</i> (2002), point out that English has only <b>two inflected tenses</b>, present and past (in their terms, present and preterite): <i>sail/sails</i> and <i>sailed</i>. The perfect and progressive are <b>aspect</b> constructions built with <i>have</i> and <i>be</i>, and <i>will</i> is a modal auxiliary, so the "future" is a modal construction rather than an inflection. <b>Mood</b> is the grammatical marking of a clause's status as assertion, command or non-factual proposition: indicative, imperative, and the subjunctive, whose present (mandative) form is the plain base for every person (<i>that he <b>be</b></i>, <i>that she <b>leave</b></i>), and whose past form survives only as <i>were</i> with first- and third-person singular subjects (<i>if I were</i>; Huddleston and Pullum's "irrealis <i>were</i>"). Modal auxiliaries express <b>epistemic</b> modality (what is possible or necessarily true: <i>It must be late</i>) and <b>deontic</b> modality (obligation and permission: <i>You must leave</i>).</p>`,
  legend: [
    { c: "c1", sym: `S`, name: "Subject", desc: "The noun phrase the verb agrees with. In the present tense it decides <i>is/are</i>, <i>has/have</i> and the <i>-s</i> ending: <i>she sails</i>, <i>they sail</i>." },
    { c: "c2", sym: `V`, name: "Main verb", desc: "The lexical verb at the end of the verb phrase, which carries the meaning: <i>sailing</i> in <i>will have been sailing</i>. Its form is set by the auxiliary before it." },
    { c: "c3", sym: `Aux`, name: "Auxiliary", desc: "The primary auxiliaries <i>be</i>, <i>have</i>, <i>do</i> and the modals (<i>will, would, can, must</i>…). The first one is finite and carries the tense." },
    { c: "c4", sym: `S R`, name: "Time markers", desc: "On the timeline: <b>S</b>, speech time (now), and <b>R</b>, reference time, the moment the sentence is talking about." },
    { c: "c5", sym: `E`, name: "Event", desc: "The time of the event itself: a point for simple aspect, a span for progressive, a completed event before <b>R</b> for perfect." }
  ],
  steps: { title: "How to name the tense and aspect of a verb phrase", items: [
    `Find the whole <b>verb phrase</b>: the <span class="c2">main verb</span> and every <span class="c3">auxiliary</span> before it, including any split off by <i>not</i>, an adverb or an inverted subject (<i>Has she <b>ever</b> sailed?</i>).`,
    `Look at the <b>first</b> verb. If it is a past form (<i>was, had, did, sailed</i>) the tense is <b>past</b>; if it is <i>will</i> (or <i>shall</i>) the time is <b>future</b>; otherwise it is <b>present</b>.`,
    `Look for <i>have</i> followed by a past participle (<i>has sailed</i>, <i>had been</i>): that is the <b>perfect</b>.`,
    `Look for <i>be</i> followed by an <i>-ing</i> form (<i>was sailing</i>, <i>been sailing</i>): that is the <b>progressive</b>. (<i>Be</i> followed by a past participle is the passive, which is voice, not aspect.)`,
    `Combine the answers: time + perfect? + progressive? For example <i>had been sailing</i> = past + perfect + progressive = <b>past perfect progressive</b>. No <i>have</i> and no <i>be</i> + <i>-ing</i> means <b>simple</b>.`,
    `Check the <b>mood</b>: a command with no subject is imperative; a base form after <i>insist that, demand that</i> or <i>were</i> in an <i>if</i>-clause is subjunctive; otherwise the clause is indicative.`
  ] },
  example: {
    prompt: `Analyse the verbs in <i>By the time the ship docked, the sailors had been waiting for hours.</i> Name the tense and aspect of each verb phrase and say what the sentence tells us about the order of events.`,
    lines: [
      { math: `the ship <span class="c2">docked</span>`, note: "The verb phrase of the time clause is one word: docked, the past form of a regular verb (dock + -ed). No auxiliary, so simple past." },
      { math: `the sailors <span class="c3">had</span> <span class="c3">been</span> <span class="c2">waiting</span>`, note: "The main clause's verb phrase is three words. The main verb is waiting; had and been are auxiliaries." },
      { math: `<span class="c3">had</span> = past of <i>have</i>`, note: "The first verb is finite and past, so the tense is past." },
      { math: `<span class="c3">had</span> + <span class="c3">been</span> (past participle)`, note: "Have followed by a past participle: perfect aspect." },
      { math: `<span class="c3">been</span> + <span class="c2">waiting</span> (-ing)`, note: "Be followed by a present participle: progressive aspect. Together: past perfect progressive." },
      { math: `<span class="c5">E</span> (waiting) ends at <span class="c4">R</span> (docking) &lt; <span class="c4">S</span>`, note: "The docking sets the reference time R in the past. The waiting is a span that began earlier and ran up to R." },
      { math: `the sailors <span class="c3">have</span> <span class="c3">been</span> <span class="c2">waiting</span>`, note: "Check by transformation: move the sentence to the present. Only the first verb changes (had → have), which shows that tense lives on the first, finite verb." }
    ],
    answer: `<i>docked</i> is simple past; <i>had been waiting</i> is past perfect progressive. The waiting began before the ship docked and was still going on when it docked.`
  },
  why: `<p>Verbs carry more grammar than any other word class, and most usage questions are verb questions: <i>lay</i> or <i>lie</i>, <i>I saw</i> or <i>I seen</i>, <i>if I was</i> or <i>if I were</i>, <i>has</i> or <i>have</i>. Tense consistency is a basic standard of college writing: a narrative that slips between past and present without reason confuses the reader about when things happen, and the past perfect is how a writer steps back from a past moment to an earlier one. Academic disciplines even have tense conventions. Writing about literature uses the "literary present" (<i>Scrooge refuses</i>), while lab reports describe procedures in the past.</p>
<p>Tense, aspect and mood are also where English differs most from other languages a student may learn. Spanish and French mark aspect inside the past tense (preterite against imperfect) and use the subjunctive far more often than English; many languages have no progressive at all. Seeing the English system clearly, with its two real tenses and its auxiliaries doing the rest, makes those systems easier to learn and explains the errors learners of English make.</p>`,
  careers: [
    { role: "Copy editor", use: "Fixes tense shifts and wrong verb forms (lay/lie, sank/sunk) and queries the author where a past perfect is needed to keep events in order." },
    { role: "ESL / EFL teacher", use: "Teaches the perfect and progressive with timelines, and explains why learners say 'I am knowing' or 'I have seen him yesterday'." },
    { role: "Contract drafter or paralegal", use: "Uses 'shall' for obligations, 'may' for permissions and 'must' for conditions, because courts read those modals as different legal duties." },
    { role: "Translator", use: "Maps aspect and mood between languages, for example rendering a Spanish imperfect as an English past progressive or 'used to' form." },
    { role: "Computational linguist", use: "Builds systems that extract events and their time order from text, which depends on tense, aspect and time expressions." },
    { role: "Speech-language pathologist", use: "Tracks a child's use of past -ed, third person -s and auxiliaries, which are standard markers in language assessments." },
    { role: "News editor", use: "Applies headline style, which reports past events in the simple present ('Mayor resigns') and the future with 'to' ('Council to vote')." }
  ],
  life: [
    "Choosing between 'lay' and 'lie' or 'sank' and 'sunk' when writing an email.",
    "Keeping one tense throughout a story, report or cover letter.",
    "Reading the 'shall' and 'may' clauses in a lease or terms of service.",
    "Writing 'If I were you' in a formal message.",
    "Learning a foreign language's verb tables."
  ],
  fields: [
    { name: "Linguistics", use: "Tense, aspect and mood are central topics in morphology, syntax and semantics, and in comparing languages." },
    { name: "Foreign language study", use: "Romance languages mark aspect in the past tense and use the subjunctive widely, so learners need the categories first." },
    { name: "Philosophy and logic", use: "Reichenbach's speech, reference and event times began in logic, and modal verbs are studied in modal logic." },
    { name: "Law", use: "The meaning of modal verbs such as shall, may and must in statutes and contracts is regularly argued in court." }
  ],
  prereqWhy: {
    "eng-parts-of-speech": "You need to recognise a verb (the word that changes tense) and tell it from the nouns and adjectives built from it before taking its forms apart."
  },
  unlocksWhy: {
    "eng-subject-predicate": "The predicate is built around the verb phrase, and finding the finite verb is the first step in finding the subject."
  },
  beyond: [
    { field: "Composition I", why: "Revising for tense consistency and choosing active verbs and the right verb forms are core editing skills." },
    { field: "Introduction to Literature", why: "Essays about literature use the literary present, and narrative tense and mood shape how a story is told." },
    { field: "Introduction to English Linguistics", why: "Tense, aspect, mood and the auxiliary system are analysed there with formal tests such as the NICE properties." },
    { field: "History of the English Language", why: "The two-tense Germanic system, strong verbs like sing, sang, sung, and the rise of will and do explain today's irregularities." }
  ],
  mistakes: [
    { wrong: `"English has a future tense, formed with <i>will</i>, just as it has a past tense formed with <i>-ed</i>."`, fix: `English verbs inflect for only two tenses, present (<i>sails</i>) and past (<i>sailed</i>). <i>Will</i> is a modal auxiliary like <i>can</i> and <i>must</i>, and the future is also expressed by <i>be going to</i>, the present progressive (<i>We are leaving tomorrow</i>) and even the simple present (<i>The train leaves at six</i>).` },
    { wrong: `<i>I seen it.</i> · <i>She has went home.</i> · <i>He had wrote twice.</i>`, fix: `The past form stands alone; the past participle follows <i>have</i> or <i>be</i>. <i>I <b>saw</b> it. She has <b>gone</b> home. He had <b>written</b> twice.</i> For irregular verbs, learn the principal parts as a set: <i>see, saw, seen</i>.` },
    { wrong: `<i>I am knowing the answer.</i> · <i>She is owning two boats.</i>`, fix: `Stative verbs (<i>know, own, believe, belong, contain</i>) describe states, not activities, and normally refuse the progressive: <i>I know the answer. She owns two boats.</i> Some verbs have both uses: <i>She has a boat</i> (state) but <i>She is having lunch</i> (activity).` },
    { wrong: `<i>If I was rich, I would buy a ship.</i> (in formal writing) · <i>I should of left.</i>`, fix: `Formal writing uses the subjunctive <i>were</i> for an unreal condition: <i>If I <b>were</b> rich</i>. And <i>of</i> is never an auxiliary: the spoken contraction <i>should've</i> is <i>should <b>have</b> left</i>.` }
  ],
  practice: [
    { q: `Give the five forms (base, <i>-s</i> form, past, past participle, present participle) of (a) <i>stop</i>, (b) <i>take</i>, (c) <i>study</i>. Then list the forms of <i>be</i>.`,
      a: `(a) stop, stops, stopped, stopped, stopping (regular; the final consonant doubles after a short stressed vowel). (b) take, takes, took, taken, taking (irregular; the silent <i>e</i> drops before <i>-ing</i>). (c) study, studies, studied, studied, studying (regular; <i>y</i> becomes <i>i</i> before <i>-es</i> and <i>-ed</i> but stays before <i>-ing</i>). <i>Be</i> has eight forms: base <i>be</i>; present <i>am, is, are</i>; past <i>was, were</i>; past participle <i>been</i>; present participle <i>being</i>.` },
    { q: `Name the tense and aspect: (a) <i>She had left.</i> (b) <i>They will be sailing.</i> (c) <i>I have been reading.</i> (d) <i>He walks to work.</i>`,
      a: `(a) past perfect: <i>had</i> (past) + past participle. (b) future progressive: <i>will</i> + <i>be</i> + <i>-ing</i>. (c) present perfect progressive: <i>have</i> (present) + <i>been</i> + <i>-ing</i>. (d) simple present: one present-tense verb with the third-person <i>-s</i>, here describing a habit.` },
    { q: `Fill each gap with the right form of the verb in brackets and name the mood: (a) <i>The rules require that every member ___ dues.</i> (pay) (b) <i>If I ___ you, I would wait.</i> (be) (c) <i>___ quiet!</i> (be)`,
      a: `(a) <i>pay</i>: present (mandative) subjunctive, the base form with no <i>-s</i> even though <i>member</i> is third-person singular. (b) <i>were</i>: past subjunctive (irrealis <i>were</i>) for an unreal condition. (c) <i>Be</i>: imperative, the base form with the subject <i>you</i> understood.` },
    { q: `In <i>The letter might have been written by Scrooge</i>, identify the main verb and each auxiliary, say which verb is finite, and explain why the phrase is not progressive.`,
      a: `The main verb is <i>written</i> (past participle). The auxiliaries are <i>might</i> (modal, followed by the base <i>have</i>), <i>have</i> (perfect, followed by the past participle <i>been</i>) and <i>been</i> (passive <i>be</i>, followed by the past participle <i>written</i>). <i>Might</i> is the finite verb, the first in the phrase. It is not progressive because no form of <i>be</i> is followed by an <i>-ing</i> participle: <i>been</i> + past participle is the passive. The phrase is modal + perfect + passive.` }
  ],
  stories: [
    { title: "The Best of Times", book: "A Tale of Two Cities", author: "Charles Dickens", year: 1859, kind: "Novel", where: "Book the First, Chapter I, The Period", scene: "two-cities", focus: ["lv", "ax", "v"],
      tags: { lv: { name: "Linking verb", c: "c2", test: "A main verb that joins the subject to a complement: it was the age of wisdom." }, v: { name: "Main verb", c: "c2", test: "A lexical verb with its own meaning: had, going, insisted." }, ax: { name: "Auxiliary", c: "c3", test: "A helping verb before the main verb: were going, being received." } },
      tokens: `It was_lv the best of times , it was_lv the worst of times , it was_lv the age of wisdom , it was_lv the age of foolishness , it was_lv the epoch of belief , it was_lv the epoch of incredulity , it was_lv the season of Light , it was_lv the season of Darkness , it was_lv the spring of hope , it was_lv the winter of despair , we had_v everything before us , we had_v nothing before us , we were_ax all going_v direct to Heaven , we were_ax all going_v direct the other way — in short , the period was_lv so far like the present period , that some of its noisiest authorities insisted_v on its being_ax received_v , for good or for evil , in the superlative degree of comparison only .`,
      notes: { was: "Past tense of be, used as a linking verb: it joins it to a noun-phrase complement (the best of times). There is no action; the verb only says what the time was.", had: "Main verb have, meaning possess, in the simple past. It has an object (everything, nothing), so here it is transitive.", were: "Past tense of be as an auxiliary. With going it forms the past progressive: an action in progress, seen from inside.", going: "Present participle of go, the main verb of the progressive were going.", insisted: "Simple past of a regular verb (insist + -ed), intransitive here, with its complement on its being received.", being: "Being is the -ing form of be. Here it is the passive auxiliary inside a gerund phrase: its being received means that it was received.", received: "A past participle. After the passive auxiliary being it shows the period receiving the action, not doing it." },
      note: `Dickens builds his opening on one verb: <i>was</i>, a linking verb, eleven times. It does no action; it couples <i>it</i> to a string of complements (<i>the best of times, the worst of times</i>…). Every finite verb in the sentence is past tense, the default tense of narrative, but the aspect shifts once: <i>we <b>were</b> all <b>going</b></i> is past progressive, picturing a whole society in mid-motion. <i>Had</i> appears twice as a main verb meaning "possessed", which shows that <i>have</i> is not always an auxiliary.` },
    { title: "We Are Met on a Great Battlefield", book: "Lincoln's Gettysburg Address", author: "Abraham Lincoln", year: 1863, kind: "Speech", where: "Gettysburg, Pennsylvania, 19 November 1863", scene: "battlefield", focus: ["ax", "md", "v", "lv"],
      tags: { ax: { name: "Primary auxiliary", c: "c3", test: "be, have or do before a main verb." }, md: { name: "Modal auxiliary", c: "c3", test: "can, could, may, might, must, shall, should, will, would + base form." }, v: { name: "Main verb", c: "c2" }, lv: { name: "Linking verb", c: "c2" } },
      tokens: `We are_ax met_v on a great battlefield of that war . ¶ We have_ax come_v to dedicate_v a portion of that field as a final resting place for those who here gave_v their lives that this nation might_md live_v . It is_lv altogether fitting and proper that we should_md do_v this .`,
      notes: { are: "An old perfect auxiliary. Earlier English made the perfect of some verbs of motion and coming together with be instead of have: we are met means we have met (have assembled). Compare the hour is come in the King James Bible.", met: "Past participle of the irregular verb meet (meet, met, met).", have: "Present tense of have as the perfect auxiliary: have come is present perfect, a past event (coming here) seen from the present.", come: "Past participle of come. Its base form and past participle are identical: come, came, come.", dedicate: "A base form after the infinitive marker to. Infinitives are non-finite: they carry no tense of their own.", gave: "Simple past of the irregular verb give (give, gave, given): the soldiers' deaths are finished past events.", might: "A modal in a purpose clause (that this nation might live). It marks the living as a hoped-for possibility, not a fact.", live: "The base form, as always after a modal.", is: "Present tense of be as a linking verb. Its complement is the pair of adjectives fitting and proper.", should: "Putative should: after it is fitting that, it presents the dedication as something judged right, not reported as fact. A mandative subjunctive (that we do this) would say much the same.", do: "Main verb do (perform an action), not do-support: it has an object, this." },
      note: `Lincoln's verbs move from past to present to possibility. <i>Are met</i> and <i>have come</i> are both perfects, the first in an older form with <i>be</i> that was already formal in 1863. <i>Gave</i> is a plain simple past for the completed sacrifice, set against two modals, <i>might live</i> and <i>should do</i>, which present the nation's survival and the dedication as goals rather than facts. <i>Do</i> here is a main verb with an object, not the auxiliary <i>do</i>.` },
    { title: "If I Could Work My Will", book: "A Christmas Carol", author: "Charles Dickens", year: 1843, kind: "Novella", where: "Stave One", scene: "counting-house", focus: ["md", "ax", "v"],
      tags: { md: { name: "Modal auxiliary", c: "c3", test: "can, could, may, might, must, shall, should, will, would + base form." }, ax: { name: "Primary auxiliary", c: "c3" }, v: { name: "Main verb", c: "c2" } },
      tokens: `“ If I could_md work_v my will , ” said_v Scrooge indignantly , “ every idiot who goes_v about with ‘ Merry Christmas ’ on his lips , should_md be_ax boiled_v with his own pudding , and buried_v with a stake of holly through his heart . He should_md#should2 ! ”`,
      notes: { could: "A past-tense modal with present, unreal meaning: if I could means if I were able (now), which Scrooge is not. This use of past forms for remoteness is called modal remoteness or the modal past.", work: "The base form after the modal could. To work one's will means to do what one wants.", said: "Simple past of the irregular verb say (say, said, said), the narrative verb.", goes: "The -s form (third person singular present) of go. The simple present here describes a habit: every idiot who goes about saying it.", should: "The modal should marks what ought to happen in Scrooge's ideal world, not what does happen.", be: "The base form of be after the modal, working as the passive auxiliary: should be boiled.", boiled: "Past participle of the regular verb boil. After passive be the subject (every idiot) receives the action.", buried: "Past participle of bury (y changes to i before -ed). It shares should be with boiled.", should2: "He should! repeats only the modal and leaves out be boiled. Standing in for a whole verb phrase like this is the Code property that only auxiliaries have." },
      note: `Scrooge's outburst is built on modals. <i>Could</i> is past in form but present in meaning: <i>If I could</i> describes a world that does not exist. <i>Should be boiled … and buried</i> stacks a modal, the passive auxiliary <i>be</i> and two past participles. The single present-tense verb, <i>goes</i>, has the third-person <i>-s</i> because its subject <i>who</i> refers to <i>every idiot</i>. Then <i>He should!</i> shows the modal standing alone for the whole verb phrase.` },
    { title: "Netherfield Park Is Let at Last", book: "Pride and Prejudice", author: "Jane Austen", year: 1813, kind: "Novel", where: "Chapter 1", scene: "drawing-room", focus: ["ax", "v"],
      tags: { ax: { name: "Auxiliary", c: "c3", test: "be, have, do or a modal before the main verb." }, v: { name: "Main verb", c: "c2" } },
      tokens: `“ My dear Mr. Bennet , ” said_v his lady to him one day , “ have_ax you heard_v that Netherfield Park is_ax let_v at last ? ” ¶ Mr. Bennet replied_v that he had_ax not . ¶ “ But it is_ax#is2 , ” returned_v she ; “ for Mrs. Long has_ax just been_v here , and she told_v me all about it . ” ¶ Mr. Bennet made_v no answer . ¶ “ Do_ax not you want_v to know_v who has_ax#has2 taken_v it ? ” cried_v his wife , impatiently .`,
      notes: { said: "Simple past of say: the narrative tense that carries the story.", have: "Present tense have, the perfect auxiliary, inverted before the subject you to make a question.", heard: "Past participle of hear (hear, heard, heard). Have heard is present perfect: a past event that matters now.", is: "Present tense of be as the passive auxiliary: is let means has been rented out.", let: "Past participle of let (let, let, let), one of the verbs whose three forms are identical.", replied: "Simple past of reply (y becomes i before -ed).", had: "Had not stands for had not heard. Reported after a past verb, Mr. Bennet's reply I have not (heard) shifts back to the past perfect (backshift), and the auxiliary alone carries the meaning.", is2: "Is alone stands for is let: an auxiliary can stand in for the whole verb phrase.", returned: "An older sense of return, meaning replied.", has: "Present perfect auxiliary: has just been here, a very recent past event with present relevance. Just is typical with the perfect.", been: "Past participle of be, here a main verb meaning came and went (has been here).", told: "Simple past of tell. The visit is a finished event, so Mrs. Bennet switches from the present perfect to the simple past.", made: "Simple past of the irregular verb make.", do: "Do-support: want has no auxiliary of its own, so the question and the negative borrow do. Do not you (rather than Don't you or Do you not) is an older word order.", want: "The base form after do. Want is a stative verb, rarely used in the progressive.", know: "A base form after the infinitive marker to: non-finite.", has2: "Present perfect again: who has taken it means who is the new tenant now.", taken: "Past participle of the irregular verb take (take, took, taken).", cried: "Simple past of cry (y becomes i before -ed)." },
      note: `Austen's first dialogue turns on the difference between the perfect and the simple past. Mrs. Bennet uses the present perfect for news that matters now (<i>have you heard</i>, <i>has just been here</i>, <i>has taken it</i>) and the simple past for a finished event (<i>she told me</i>). The auxiliaries do a great deal on their own: <i>he had not</i> and <i>But it is</i> stand for whole verb phrases. And <i>Do not you want</i> shows do-support, the auxiliary <i>do</i> that English brings in when a verb has no auxiliary of its own.` }
  ],
  origin: `English inherited a two-tense system from Proto-Germanic: Old English verbs inflected only for present and past, and "strong" verbs formed the past by changing the vowel (<i>singan, sang</i>), the source of today's irregular verbs. The future with <i>will</i> and <i>shall</i> grew from Old English verbs meaning "want" (<i>willan</i>) and "owe, be obliged" (<i>sculan</i>); the perfect with <i>have</i> and the progressive with <i>be</i> + <i>-ing</i> became fully grammatical in Middle and Early Modern English, and do-support in questions and negatives became standard between the sixteenth and eighteenth centuries. The analysis of tenses with speech time, reference time and event time comes from the logician Hans Reichenbach's <i>Elements of Symbolic Logic</i> (1947).`
};
