# content: a58959c13fc3
# g-symmetry: Compositions of Transformations & Symmetry
from sympy import Point, Line, Matrix, sqrt as Sqrt, rad
eqp = lambda l, a, b: check(l, Point(a) == Point(b), f"{a} vs {b}")
t, u = symbols('t u', real=True)
Ref = lambda al: Matrix([[cos(2*al), sin(2*al)], [sin(2*al), -cos(2*al)]])   # reflection in the line through O at angle al
Rot = lambda th: Matrix([[cos(th), -sin(th)], [sin(th), cos(th)]])
# formal: intersecting mirrors give rotation by twice the angle; parallel mirrors give translation by 2d
check("formal", simplify(Ref(u) * Ref(t) - Rot(2*(u - t))) == zeros(2, 2), "r_m o r_l = R(2(theta))")
X0 = Point(t, u)
for d in (3, Rational(5, 2)):
    eqp("formal", X0.reflect(Line((0, 0), (0, 1))).reflect(Line((d, 0), (d, 1))), Point(t + 2*d, u))
# example
P = Point(3, 1)
P1 = P.reflect(Line((0, 0), (1, 0))); eqp("example", P1, Point(3, -1))
P2 = P1.reflect(Line((0, 0), (1, 1))); eqp("example", P2, Point(-1, 3))
v = Rot(2*pi/4) * Matrix([3, 1]); eqp("example", Point(v[0], v[1]), P2)
same("example", [P.distance(Point(0, 0)), P2.distance(Point(0, 0))], [Sqrt(10), Sqrt(10)])
same("example", P.x*P2.x + P.y*P2.y, 0)
same("example", 360/45, 8); same("example", 360/90, 4)
# 4 mirror lines: the group generated by mirrors at 0 and 45 degrees contains reflections at 0, 45, 90, 135 only
mir = sorted({(a + 2*k*45) % 180 for a in (0, 45) for k in range(4)})
same("example", mir, [0, 45, 90, 135])
# practice[0]: lines of symmetry of regular n-gon = n; order n; point symmetry iff n even
def mirrors(n):
    V = [Matrix([cos(2*pi*j/n), sin(2*pi*j/n)]) for j in range(n)]
    key = lambda M: (round(float(M[0]), 9), round(float(M[1]), 9))
    S = {key(v) for v in V}; cnt = 0
    for j in range(2*n):   # candidate mirror angles j*180/(2n) degrees
        R = Ref(pi*j/(2*n))
        if {key(R*v) for v in V} == S: cnt += 1
    return cnt
same("practice[0]", mirrors(6), 6); same("practice[0]", mirrors(5), 5)
same("practice[0]", Rational(360, 6), 60); same("practice[0]", Rational(360, 5), 72)
check("practice[0]", 180 % 72 != 0 and 180 % 60 == 0, "pentagon no point symmetry, hexagon has it")
# practice[1]
x1, x6 = Line((1, 0), (1, 1)), Line((6, 0), (6, 1))
P = Point(2, 5)
eqp("practice[1]", P.reflect(x1), Point(0, 5)); eqp("practice[1]", P.reflect(x1).reflect(x6), Point(12, 5))
same("practice[1]", 12 - 2, 2*(6 - 1))
eqp("practice[1]", P.reflect(x6), Point(10, 5)); eqp("practice[1]", P.reflect(x6).reflect(x1), Point(-8, 5))
# practice[2]
al = rad(35)
check("practice[2]", simplify(Ref(al) * Ref(0) - Rot(rad(70))) == zeros(2, 2), "r_m o r_l is +70 deg")
check("practice[2]", simplify(Ref(0) * Ref(al) - Rot(-rad(70))) == zeros(2, 2), "r_l o r_m is -70 deg")
check("practice[2]", simplify(Rot(-rad(70)) - Rot(rad(290))) == zeros(2, 2), "-70 = 290")
# practice[3]
xa = Line((0, 0), (1, 0))
G = lambda Q: (Q + Point(4, 0)).reflect(xa)
eqp("practice[3]", Point(1, 2) + Point(4, 0), Point(5, 2)); eqp("practice[3]", G(Point(1, 2)), Point(5, -2))
eqp("practice[3]", Point(-3, 4) + Point(4, 0), Point(1, 4)); eqp("practice[3]", G(Point(-3, 4)), Point(1, -4))
eqp("practice[3]", G(G(Point(1, 2))), Point(9, 2)); eqp("practice[3]", G(G(X0)), X0 + Point(8, 0))
eqp("practice[3]", (Point(1, 2).reflect(xa)) + Point(4, 0), G(Point(1, 2)))   # translation and reflection commute
