/* Glossary: English. One block per headword (and part of speech). Spec: web/GLOSSARY-SPEC.md.
   Vocabulary entries carry field "vocabulary" and the node that teaches them; grammar terms carry field "grammar". */
DB.addGlossary("english", [
  { w: "root", field: "vocabulary", node: "voc-morphemes", pos: "n", ipa: "/rut/",
    senses: ["The core morpheme of a word, which carries its basic meaning and to which affixes attach: <i>dict</i> in <i>predict</i> and <i>diction</i>.",
      "The older word a word descends from, especially a Latin or Greek one."],
    origin: "Late Old English <i>rōt</i>, from Old Norse <i>rót</i>", forms: ["roots"], see: ["morpheme","prefix","suffix","polysemy"] },
  { w: "morpheme", field: "vocabulary", node: "voc-morphemes", pos: "n", ipa: "/ˈmɔrfim/", syl: "mor·pheme", register: "technical",
    senses: ["The smallest unit of language that has a meaning or a grammatical job. <i>Unbreakable</i> has three: <i>un-</i>, <i>break</i>, <i>-able</i>.",
      "A <b>free</b> morpheme can stand alone as a word (<i>break</i>); a <b>bound</b> morpheme cannot (<i>un-</i>, <i>-able</i>)."],
    parts: [["morph","form"],["eme","unit of a language system"]],
    origin: "French <i>morphème</i> (1890s), from Greek <i>morphē</i> ‘form’, on the model of <i>phonème</i>", forms: ["morphemes"], see: ["root","prefix","suffix"] },
  { w: "prefix", field: "vocabulary", node: "voc-prefixes", pos: "n", ipa: "/ˈpriˌfɪks/", syl: "pre·fix",
    senses: ["An affix attached to the front of a base: <i>un-</i> in <i>unclear</i>, <i>sub-</i> in <i>submarine</i>. A prefix usually changes a word’s meaning but not its part of speech."],
    parts: [["pre","before"],["fix","fasten"]], origin: "Latin <i>praefixus</i>, from <i>praefigere</i> ‘to fasten in front’", forms: ["prefixes"], see: ["suffix","morpheme"] },
  { w: "suffix", field: "vocabulary", node: "voc-suffixes", pos: "n", ipa: "/ˈsʌfɪks/", syl: "suf·fix",
    senses: ["An affix attached to the end of a base: <i>-ness</i> in <i>kindness</i>, <i>-ize</i> in <i>modernize</i>.",
      "<b>Derivational</b> suffixes make new words and often change the part of speech (<i>analyze → analysis</i>); <b>inflectional</b> suffixes mark grammar (<i>-s</i>, <i>-ed</i>, <i>-ing</i>)."],
    parts: [["suf","under, after (a form of <i>sub-</i>)"],["fix","fasten"]], origin: "Latin <i>suffixus</i>, from <i>sub</i> ‘under’ + <i>figere</i> ‘to fasten’", forms: ["suffixes"], see: ["prefix","morpheme"] },
  { w: "benediction", field: "vocabulary", node: "voc-latin-roots", pos: "n", ipa: "/ˌbɛnəˈdɪkʃən/", syl: "ben·e·dic·tion", register: "formal", conno: "positive",
    senses: ["A blessing, especially one spoken at the end of a religious service.", "Any spoken expression of good wishes or approval."],
    parts: [["bene","well"],["dict","say"],["ion","act or result of"]], origin: "Latin <i>benedictio</i>, from <i>benedicere</i> ‘to speak well of, to bless’",
    ant: ["malediction"], forms: ["benedictions"], see: ["predict"] },
  { w: "predict", field: "vocabulary", node: "voc-latin-roots", pos: "v", ipa: "/prɪˈdɪkt/", syl: "pre·dict",
    senses: ["To say ahead of time that something will happen, usually on the basis of evidence or reasoning."],
    ex: "From thirty years of data, the model <i>predicts</i> a steady rise in sea level.",
    parts: [["pre","before"],["dict","say"]], origin: "Latin <i>praedicere</i> ‘to foretell’, from <i>prae</i> ‘before’ + <i>dicere</i> ‘to say’",
    syn: [["forecast","predict from patterns, especially weather or the economy"],["foretell","literary; often without evidence"]],
    forms: ["predicts","predicted","predicting"], see: ["benediction"] },
  { w: "chronology", field: "vocabulary", node: "voc-greek-roots", pos: "n", ipa: "/krəˈnɑlədʒi/", syl: "chro·nol·o·gy",
    senses: ["The order in which events happened.", "A list or account of events arranged in time order."],
    parts: [["chron","time"],["o","combining vowel"],["logy","account, study"]], origin: "Greek <i>khronos</i> ‘time’ + <i>-logia</i> ‘account, study’", forms: ["chronologies"], see: ["etymology"] },
  { w: "etymology", field: "vocabulary", node: "voc-etymology", pos: "n", ipa: "/ˌɛtəˈmɑlədʒi/", syl: "et·y·mol·o·gy",
    senses: ["The origin and history of a word: where it came from and how its form and meaning changed.", "The study of word origins."],
    parts: [["etym","true sense"],["o","combining vowel"],["logy","study"]], origin: "Greek <i>etumologia</i>, from <i>etumon</i> ‘the true sense of a word’ + <i>-logia</i>",
    confused: [["entomology","the study of insects"]], forms: ["etymologies"], see: ["chronology","root"] },
  { w: "polysemy", field: "vocabulary", node: "voc-polysemy", pos: "n", ipa: "/pəˈlɪsəmi/", syl: "po·lys·e·my", register: "technical",
    senses: ["The existence of several related meanings for one word. <i>Root</i> names part of a plant, the core of a word, a solution of an equation and the base note of a chord: open it in the glossary to see each subject’s sense."],
    parts: [["poly","many"],["sem","sign, meaning"],["y","state of"]], origin: "Greek <i>polusēmos</i> ‘having many meanings’, from <i>polus</i> ‘many’ + <i>sēma</i> ‘sign’",
    see: ["root","degree","function"] },
  { w: "denotation", field: "vocabulary", node: "voc-connotation", pos: "n", ipa: "/ˌdinoʊˈteɪʃən/", syl: "de·no·ta·tion",
    senses: ["The literal, dictionary meaning of a word, apart from the feelings it suggests."],
    parts: [["de","fully"],["not","mark"],["ation","act, result"]], origin: "Latin <i>denotare</i> ‘to mark out’, from <i>de-</i> + <i>notare</i> ‘to mark’", forms: ["denotations"], see: ["connotation"] },
  { w: "connotation", field: "vocabulary", node: "voc-connotation", pos: "n", ipa: "/ˌkɑnəˈteɪʃən/", syl: "con·no·ta·tion",
    senses: ["The feelings and associations a word carries beyond its literal meaning: <i>thrifty</i> and <i>stingy</i> share a denotation but differ in connotation."],
    parts: [["con","with, together"],["not","mark"],["ation","act, result"]], origin: "Medieval Latin <i>connotatio</i>, from <i>connotare</i> ‘to mark along with’", forms: ["connotations"], see: ["denotation","frugal"] },
  { w: "frugal", field: "vocabulary", node: "voc-synonyms", pos: "aj", ipa: "/ˈfruɡəl/", syl: "fru·gal", conno: "positive",
    senses: ["Careful and sparing with money or resources; not wasteful."],
    ex: "A <i>frugal</i> household plans its meals around what is already in the cupboard.",
    syn: [["thrifty","approving; good at saving"],["economical","neutral; avoids waste"],["stingy","disapproving; unwilling to spend or give"],["miserly","strongly disapproving; hoards money"]],
    ant: ["extravagant","wasteful"], origin: "Latin <i>frugalis</i>, from <i>frugi</i> ‘useful, honest, thrifty’", see: ["connotation"] },
  { w: "register", field: "vocabulary", node: "voc-register", pos: "n", ipa: "/ˈrɛdʒɪstɚ/", syl: "reg·is·ter",
    senses: ["The level of formality chosen for a situation and audience: formal <i>commence</i>, neutral <i>begin</i>, informal <i>kick off</i>."],
    origin: "Medieval Latin <i>registrum</i>, from Latin <i>regesta</i> ‘things recorded’", forms: ["registers"] },
  { w: "affect", field: "vocabulary", node: "voc-confusables", pos: "v", ipa: "/əˈfɛkt/", syl: "af·fect",
    senses: ["To act on or influence: <i>The cold spring affected the harvest.</i>", "(Formal) To put on a show of a feeling or manner: <i>She affected indifference.</i>"],
    confused: [["effect","usually a noun, a result: <i>the effect of the cold</i>. As a verb, <i>to effect a change</i> means to bring it about."]],
    origin: "Latin <i>afficere</i> ‘to act on, influence’, from <i>ad-</i> ‘to’ + <i>facere</i> ‘to do’", forms: ["affects","affected","affecting"], see: ["effect"] },
  { w: "effect", field: "vocabulary", node: "voc-confusables", pos: "n", ipa: "/ɪˈfɛkt/", syl: "ef·fect",
    senses: ["A change that results from an action or cause: <i>the effect of the cold on the harvest</i>.", "The impression a work makes on a reader, viewer or listener."],
    confused: [["affect","usually a verb, to influence: <i>the cold affected the harvest</i>"]],
    origin: "Latin <i>effectus</i>, from <i>efficere</i> ‘to accomplish’, from <i>ex-</i> ‘out’ + <i>facere</i> ‘to do’", forms: ["effects"], see: ["affect"] },
  { w: "analyze", field: "vocabulary", node: "voc-academic-words", pos: "v", ipa: "/ˈænəˌlaɪz/", syl: "an·a·lyze", register: "formal",
    senses: ["To examine something closely by separating it into its parts and studying how the parts relate."],
    ex: "The essay <i>analyzes</i> how Dickens builds his opening from paired opposites.",
    parts: [["ana","up, throughout"],["lyze","loosen"]], origin: "From <i>analysis</i>: Greek <i>analusis</i>, from <i>analuein</i> ‘to unloose’ (<i>ana-</i> ‘up’ + <i>luein</i> ‘to loosen’)",
    syn: [["examine","more general; look at closely"],["dissect","stronger; take apart piece by piece"]], forms: ["analyzes","analyzed","analyzing","analyse"] },
  { w: "derive", field: "vocabulary", node: "voc-academic-words", pos: "v", ipa: "/dɪˈraɪv/", syl: "de·rive", register: "formal",
    senses: ["To get something from a source: <i>English derives many words from Latin.</i>", "To reach a result by reasoning or calculation: <i>derive a formula</i>."],
    parts: [["de","from, away"],["riv","stream"]], origin: "Old French <i>deriver</i>, from Latin <i>derivare</i> ‘to draw off (water)’, from <i>de-</i> + <i>rivus</i> ‘stream’", forms: ["derives","derived","deriving"] },
  { w: "factor", field: "vocabulary", node: "voc-academic-words", pos: "n", ipa: "/ˈfæktɚ/", syl: "fac·tor", register: "formal",
    senses: ["One of the circumstances or influences that together produce a result: <i>Cost was a major factor in the decision.</i>"],
    origin: "Latin <i>factor</i> ‘doer, maker’, from <i>facere</i> ‘to do, to make’", forms: ["factors"] },
  { w: "stress", field: "vocabulary", node: "voc-stress", pos: "n", ipa: "/strɛs/",
    senses: ["Extra force on a syllable in speech, making it louder, longer or higher: noun <i>PREsent</i>, verb <i>preSENT</i>. Dictionaries mark it with ˈ before the syllable.", "Emphasis on one word in a sentence."],
    origin: "Middle English, shortened from <i>distress</i> (Old French <i>destresse</i>)", see: ["present"] },
  { w: "present", field: "vocabulary", node: "voc-stress", pos: "aj", ipa: "/ˈprɛzənt/", syl: "pres·ent",
    senses: ["Existing or happening now: <i>the present period</i>.", "In a particular place; not absent."],
    quote: { topic: "eng-verbs", text: "the period was so far like the present period" },
    origin: "Latin <i>praesens</i> ‘being at hand’", see: ["stress"] },
  { w: "present", field: "vocabulary", node: "voc-stress", pos: "v", ipa: "/prɪˈzɛnt/", syl: "pre·sent",
    senses: ["To give formally: <i>present an award</i>.", "To offer for others to see or consider: <i>present the evidence</i>."],
    origin: "Old French <i>presenter</i>, from Latin <i>praesentare</i> ‘to place before’", forms: ["presents","presented","presenting"], see: ["stress"] },
  { w: "degree", field: "grammar", node: "eng-modifiers", pos: "n", ipa: "/dɪˈɡri/", syl: "de·gree",
    senses: ["The form of an adjective or adverb that shows how much of a quality is meant: positive <i>cold</i>, comparative <i>colder</i>, superlative <i>coldest</i>."],
    quote: { topic: "eng-verbs", text: "in the superlative degree of comparison only" },
    origin: "Old French <i>degré</i>, from Latin <i>de-</i> ‘down’ + <i>gradus</i> ‘step’", forms: ["degrees"], see: ["polysemy"] },
  { w: "function", field: "grammar", node: "eng-function-words", pos: "n", ipa: "/ˈfʌŋkʃən/", syl: "func·tion",
    senses: ["The job a word or phrase does in a sentence (subject, object, modifier), as distinct from its part of speech.",
      "<b>Function word</b>: a word whose main job is grammatical rather than carrying content, such as an article, preposition, conjunction or auxiliary (<i>the, of, and, will</i>)."],
    origin: "Latin <i>functio</i> ‘performance’, from <i>fungi</i> ‘to perform’", forms: ["functions"], see: ["polysemy"] },
  { w: "phrase", field: "grammar", node: "eng-phrases", pos: "n", ipa: "/freɪz/",
    senses: ["A group of related words that works as one unit in a sentence but has no subject–verb pair of its own: <i>in the morning</i>, <i>the old house</i>."],
    origin: "Latin <i>phrasis</i>, from Greek <i>phrasis</i> ‘way of speaking’, from <i>phrazein</i> ‘to tell’", forms: ["phrases"] },
  { w: "voice", field: "grammar", node: "eng-voice", pos: "n", ipa: "/vɔɪs/",
    senses: ["The sound a person makes in speaking or singing.",
      "(Grammar) The form of a verb that shows whether the subject acts (active: <i>The dog bit the man</i>) or is acted on (passive: <i>The man was bitten</i>)."],
    quote: { topic: "eng-commas", text: "cried a cheerful voice" },
    origin: "Old French <i>vois</i>, from Latin <i>vox</i> ‘voice’", forms: ["voices"] },
  { w: "tense", field: "grammar", node: "eng-verbs", pos: "n", ipa: "/tɛns/",
    senses: ["The form of a verb that places an action in time. English marks two tenses by inflection, present (<i>walks</i>) and past (<i>walked</i>); future time uses auxiliaries such as <i>will</i>."],
    origin: "Old French <i>tens</i> ‘time’, from Latin <i>tempus</i>", forms: ["tenses"] },
  { w: "case", field: "grammar", node: "eng-nouns-pronouns", pos: "n", ipa: "/keɪs/",
    senses: ["The form of a noun or pronoun that shows its job in the sentence: subjective <i>I</i>, objective <i>me</i>, possessive <i>my</i>, <i>mine</i>. In modern English only pronouns and the possessive <i>’s</i> show case."],
    origin: "Latin <i>casus</i> ‘a falling’, translating Greek <i>ptōsis</i>; from <i>cadere</i> ‘to fall’", forms: ["cases"] },
  { w: "period", field: "grammar", pos: "n", ipa: "/ˈpɪriəd/", syl: "pe·ri·od",
    senses: ["A length of time, especially one marked by particular features: <i>the present period</i>.", "The mark (.) that ends a declarative sentence or an abbreviation."],
    quote: { topic: "eng-verbs", text: "the period was so far like the present period" },
    origin: "Greek <i>periodos</i> ‘circuit, a going round’, from <i>peri</i> ‘around’ + <i>hodos</i> ‘way’", forms: ["periods"] },
  { w: "mass", pos: "n", ipa: "/mæs/",
    senses: ["A large number or amount; the greater part of a group: <i>the mass of men</i>.", "A body of matter with no definite shape."],
    quote: { topic: "eng-style", text: "The mass of men lead lives of quiet desperation." },
    origin: "Latin <i>massa</i> ‘lump, dough’, from Greek <i>maza</i> ‘barley cake’", forms: ["masses"] },
  { w: "work", pos: "n", ipa: "/wɝk/",
    senses: ["Effort directed toward a purpose; a task or undertaking.", "Something produced by effort, such as a book, painting or piece of music."],
    quote: { topic: "eng-agreement", text: "the unfinished work which they who fought here have thus far so nobly advanced" },
    origin: "Old English <i>weorc</i>", forms: ["works"] },
  { w: "power", pos: "n", ipa: "/ˈpaʊɚ/", syl: "pow·er",
    senses: ["The ability to do or bring about something.", "Control or authority over people or events."],
    quote: { topic: "eng-agreement", text: "far above our poor power to add or detract" },
    origin: "Anglo-Norman <i>poer</i>, from Latin <i>posse</i> ‘to be able’", forms: ["powers"] },
  { w: "argument", field: "comp-2", pos: "n", ipa: "/ˈɑrɡjəmənt/", syl: "ar·gu·ment",
    senses: ["A claim supported by reasons and evidence, meant to persuade a reader.", "A disagreement, often a heated one."],
    origin: "Latin <i>argumentum</i>, from <i>arguere</i> ‘to make clear, to prove’", forms: ["arguments"] }
]);
